# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build-test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: |
          ./gradlew build fmu4j
          ls build/fmus
      - name: save fmu
        uses: actions/upload-artifact@v2
        with:
          name: fmus
          path: build/fmus
          
  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: Download python package
        uses: actions/download-artifact@v1
        with:
          name: fmus
          
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
                          
      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      
      - name: Run the Tests
        run: |
          echo "JavaHome: $JAVA_HOME"
          echo "Path: $PATH"
          echo "Runner: $RUNNER_OS"
          echo "$JAVA_HOME/jre/bin/server" >> $GITHUB_PATH
          echo "GITHUB_PATH: $GITHUB_PATH"
          if: runner.os == 'Linux'
            export LD_LIBRARY_PATH="$JAVA_HOME/jre/lib/amd64/server:${LD_LIBRARY_PATH}"
          if [ "$RUNNER_OS" == "Linux" ]; then
            export LD_LIBRARY_PATH="$JAVA_HOME/jre/lib/amd64/server:${LD_LIBRARY_PATH}"
          elif [ "$RUNNER_OS" == "Windows" ]; then
            export PATH="$JAVA_HOME/jre/bin/server:${PATH}"
            export PATH="/c/hostedtoolcache/windows/Java_Adopt_jdk/8.0.312-7/x64/jre/bin/server:${PATH}"
          fi
          echo "Path: $PATH"
          # Install  dependencies
          python -m pip install fmpy[complete]
          mkdir -p build/fmus && cp fmus/JavaSlave.fmu build/fmus
          cd test
          python test-fmu.py
        shell: bash
        
