# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build-test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: |
          ./gradlew build fmu4j
          ls build/fmus
      - name: save fmu
        uses: actions/upload-artifact@v2
        with:
          name: fmus
          path: build/fmus
          
  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: Download python package
        uses: actions/download-artifact@v1
        with:
          name: fmus
          
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Setup Python 39
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9
          
      - name: Run the Tests
        shell: bash -l {0}
        run: |
          conda activate test
          # Install  dependencies
          conda install -c conda-forge pyfmi
          mkdir -p build/fmus && cp fmus/JavaSlave.fmu build/fmus
          cd test
          python test-fmu.py
        
